import Head from "next/head"
import Link from "next/link"
import Image from "next/image"
import { ReactNode, useMemo } from "react";
import Footer from "./Footer";

type LayoutProps = {
  title: string;
  children: ReactNode;
}
export const Layout = ({children, title = "Page title"} : LayoutProps) => {
  return useMemo(() => {
    return (
      <>
        <div className={"min-h-screen flex flex-col justify-center items-center text-gray-600 text-sm font-mono"}>
          <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <header>
            <nav className="bg-gray-800 w-screen">
              <div className="flex items-center pl-8 h-14">
                <div className="flex space-x-4">
                  <Link href="/">
                    <a className="text-gray-300 hover:bg-gray-700 px-3 py-2 rounded">
                      Home
                    </a>
                  </Link>
                  <Link href="/blog">
                    <a className="text-gray-300 hover:bg-gray-700 px-3 py-2 rounded">
                      Blog
                    </a>
                  </Link>
                  <Link href="/contact">
                    <a className="text-gray-300 hover:bg-gray-700 px-3 py-2 rounded">
                      Contact
                    </a>
                  </Link>
                </div>
              </div>
            </nav>
          </header>
          <main className="flex flex-1 justify-center items-center flex-col w-screen">
            {children}
          </main>
          <Footer />
        </div>
      </>
    )
  },[children, title])
}
